#!/usr/bin/env python3
"""phase.py - run a whole pipeline phase in the correct order, once.

Why this exists
---------------
The per-step tools in this directory are good. The ORDER they run in is the
part that keeps going wrong, because it is written prose in CLAUDE.md and prose
does not fail loudly. In a single session on 2026-08-05 the regeneration
recipe was got wrong twice, and each mistake looked like a different bug:

  * copying only `*.c` left a stale recomp_funcs.h beside new sources, and the
    single symptom was one undeclared identifier out of recomp_dispatch.c. It
    reads exactly like a generator bug and is not.
  * PowerShell's Copy-Item PRESERVES mtimes, so copied files looked older than
    the .obj files, ninja skipped recompiling them, and the link failed with
    hundreds of phantom LNK2019s from a half-old object set.
  * recomp_seed.c is not regenerated by the lifter and must be rebuilt BEFORE
    stub_overridden.py, which strips generated bodies it believes recomp_seed.c
    provides. With a stale seed file it stripped 994 instead of 871.

None of those are interesting problems. They are ordering, and ordering is what
a script is for.

Phases
------
  rebuild   regenerate gen/ from the XBE and re-apply everything on top
  reseed    re-seed + re-apply, without regenerating (after editing seed_list)
  verify    build, run twice, report the tracked signals
  status    where is the boot right now, and what is the next question

Usage (from src/game/):
    py -3 tools_data/phase.py status
    py -3 tools_data/phase.py reseed
    py -3 tools_data/phase.py verify
    py -3 tools_data/phase.py rebuild --gen-dir <scratch>/gen_new
    ... add --dry-run to any of them to print the steps without running

Portability note
----------------
The phase ORDER here is not specific to this title - any recompile of this
shape has the same dependencies (generate -> seed -> stub -> dedupe -> re-apply
hand edits -> build -> measure). The individual tool names are this project's.
Keep the sequencing here and swap the commands to reuse it elsewhere.
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(GAME))
PY = [sys.executable or "py"]


def run(cmd, dry, cwd=GAME, allow_fail=False):
    """Run one step. A step that fails stops the phase unless allow_fail."""
    shown = " ".join(cmd if isinstance(cmd, list) else [cmd])
    print(f"\n$ {shown}")
    if dry:
        return 0
    r = subprocess.run(cmd, cwd=cwd, shell=isinstance(cmd, str))
    if r.returncode and not allow_fail:
        print(f"\n!! step failed (exit {r.returncode}) - stopping the phase "
              f"here rather than running later steps on a broken tree")
        sys.exit(r.returncode)
    return r.returncode


def tool(name, *args):
    return PY + [os.path.join("tools_data", name), *args]


def phase_reseed(a):
    """Re-seed and re-apply. Use after editing seed_list.json."""
    run(tool("seed_missing_functions.py", "--from-list", "seed_list.json",
             "--apply"), a.dry_run)
    # MUST follow seeding: it strips generated bodies it believes recomp_seed.c
    # now provides, so a stale seed file makes it strip the wrong set.
    run(tool("stub_overridden.py", "--apply"), a.dry_run)
    run(tool("dedupe_seed.py", "--apply"), a.dry_run)
    # MUST follow every step that rewrites bodies, and precede the hand edits.
    # The lifter emits an x86 `cmp` as a comment and re-evaluates the test
    # inside the following jcc, so an instruction between them that writes an
    # operand makes the branch read the wrong value. Regeneration reintroduces
    # the whole class every time; leaving this out of the pipeline is how
    # ledger #44's repair was silently lost and 466 sites came back (#210).
    run(tool("fix_stale_flags.py", "--apply"), a.dry_run)
    # Hand edits last - the steps above rewrite bodies they anchor into.
    run(tool("manual_edits.py", "apply"), a.dry_run, allow_fail=True)
    run(tool("manual_edits.py", "apply"), a.dry_run, allow_fail=True)
    run(tool("manual_edits.py", "check-braces"), a.dry_run)


def phase_rebuild(a):
    if not a.gen_dir:
        sys.exit("--gen-dir <scratch dir> is required for rebuild")
    print("!! snapshot first if you have not - gen/ is an artefact, not a "
          "derivation:\n     py -3 tools_data/snapshot.py -m \"before regen\"")
    run(PY + ["-m", "tools.recomp", "game/default.xbe", "--all", "--split",
              "1000", "--gen-dir", a.gen_dir, "--functions",
              "seeded_functions.json", "--skip-binary-check"],
        a.dry_run, cwd=REPO)

    gen = os.path.join(GAME, "src", "recomp", "gen")
    print(f"\n$ copy {a.gen_dir}/*.c AND *.h -> {gen}   (headers too: a stale "
          f"recomp_funcs.h yields one bogus C2065)")
    if not a.dry_run:
        import shutil
        import glob as _g
        n = 0
        for pat in ("*.c", "*.h"):
            for src in _g.glob(os.path.join(a.gen_dir, pat)):
                shutil.copy2(src, gen)
                # copy2 preserves mtime, which is exactly the trap - stamp it
                # forward so the build system sees the change.
                os.utime(os.path.join(gen, os.path.basename(src)), None)
                n += 1
        # recomp_seed.c is NOT produced by the lifter; it survives the copy and
        # is rebuilt by the reseed phase below.
        print(f"  copied {n} file(s) and stamped their mtimes")

    phase_reseed(a)


def read_signals():
    p = os.path.join(GAME, "stderr.txt")
    if not os.path.exists(p):
        return None
    t = open(p, encoding="utf-8", errors="replace").read()
    sig = {
        "kernel_calls": len(re.findall(r"\[KERNEL\] #", t)),
        "failed_icalls": len(re.findall(r"Failed to resolve VA", t)),
        "heap_allocs": len(re.findall(r"\[HEAP\] #", t)),
        "safe_stub": len(re.findall(r"\[SAFE_STUB\]", t)),
    }
    sig["ending"] = ("HANG" if "[WATCHDOG]" in t
                     else "CRASH" if "[CRASH]" in t else "clean/unknown")
    return sig


def phase_verify(a):
    run(PY + [os.path.join("tools_data", "smoke_spread.py"), "2"], a.dry_run)


def phase_status(a):
    sig = read_signals()
    if not sig:
        print("no stderr.txt - build and run first")
        return
    print("last run")
    for k in ("kernel_calls", "failed_icalls", "heap_allocs", "safe_stub"):
        print(f"  {k:<14} {sig[k]}")
    print(f"  {'ending':<14} {sig['ending']}")

    base = os.path.join(HERE, "smoke_baseline.json")
    if os.path.exists(base):
        b = json.load(open(base))
        print(f"\nbaseline        {b.get('min_kernel_calls')}/"
              f"{b.get('max_failed_icalls')}/{b.get('min_heap_allocs')}/"
              f"{b.get('max_safe_stub')}   (recorded {b.get('recorded_utc','?')[:10]})")

    print("\nnext question:")
    if sig["ending"] == "HANG":
        print("  A hang names nothing by itself. Capture the spinning function:")
        print("    RECOMP_HANG_RIP=1  <run>   then  triage_crash.py")
        print("  (bounded: a hard deadline terminates the run either way)")
    elif sig["ending"] == "CRASH":
        print("  py -3 tools_data/triage_crash.py        # site, registers, "
              "faulting expression")
    if sig["failed_icalls"]:
        print("  py -3 tools_data/find_icall_gaps.py     # are any of those "
              f"{sig['failed_icalls']} failures MISSING FUNCTIONS?")
        print("      seeding a real one has been the highest-yield fix "
              "available, three times over")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="phase", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("phase", choices=["rebuild", "reseed", "verify", "status"])
    ap.add_argument("--gen-dir", help="scratch dir for rebuild")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the steps in order without running them")
    a = ap.parse_args(argv)
    {"rebuild": phase_rebuild, "reseed": phase_reseed,
     "verify": phase_verify, "status": phase_status}[a.phase](a)
    return 0


if __name__ == "__main__":
    sys.exit(main())
