/**
 * YOUR_GAME_NAME - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       YOUR_GAME_NAME
 *   Title ID:    0x00000000
 *   Base addr:   0x00010000
 *   Entry point: 0x00000000
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <process.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

extern uint32_t g_eax, g_ecx, g_edx, g_esp;
extern uint32_t g_ebx, g_esi, g_edi;
extern uint32_t g_seh_ebp;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x001A1C97  /* XBE entry point VA */
#define YOUR_GAME_XBE_PATH      "game\\default.xbe"
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Dispatch table lookups (generated by recomp pipeline) */
typedef void (*recomp_func_t)(void);
extern recomp_func_t recomp_lookup(uint32_t xbox_va);

/* ── Crash-report helpers ──────────────────────────────────── */

/*
 * Actual load range of this executable.
 *
 * ASLR means we are NOT at the PE header's preferred base of 0x140000000 -
 * a 64-bit EXE typically lands near 0x7FF6'00000000. An earlier version of
 * the stack walk below filtered frames against the preferred base, so it
 * matched nothing and printed an empty stack on every crash, and the RVA in
 * the crash line was computed unconditionally and so was meaningless
 * whenever the fault was inside a system DLL.
 */
static uintptr_t g_mod_base;
static uintptr_t g_mod_end;

static void module_range(void)
{
    if (g_mod_base) return;
    HMODULE m = GetModuleHandleA(NULL);
    IMAGE_DOS_HEADER *dos = (IMAGE_DOS_HEADER *)m;
    IMAGE_NT_HEADERS *nt = (IMAGE_NT_HEADERS *)((uint8_t *)m + dos->e_lfanew);
    g_mod_base = (uintptr_t)m;
    g_mod_end = g_mod_base + nt->OptionalHeader.SizeOfImage;
}

static int in_module(uintptr_t a)
{
    module_range();
    return a >= g_mod_base && a < g_mod_end;
}

/* Print RIP, and its RVA only when the RVA actually means something. When the
 * fault is inside a system DLL - a bad pointer handed to memcpy, say - name
 * that DLL instead, because an RVA against our base would be garbage. */
static void print_rip(const char *what, uintptr_t rip)
{
    module_range();
    if (in_module(rip)) {
        fprintf(stderr, "%s RIP=0x%llX (RVA=0x%llX)",
            what, (unsigned long long)rip,
            (unsigned long long)(rip - g_mod_base));
        return;
    }
    HMODULE owner = NULL;
    char name[MAX_PATH] = "<unknown module>";
    if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                           GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                           (LPCSTR)rip, &owner) && owner) {
        GetModuleFileNameA(owner, name, sizeof name);
    }
    fprintf(stderr, "%s RIP=0x%llX (NOT in this image - inside %s;"
                    " the recompiled caller is in the stack below)",
        what, (unsigned long long)rip, name);
}

/* Walk the raw stack for anything that looks like a return address into our
 * own image. Resolve the printed RVAs against build/*.map, or let
 * tools_data/triage_crash.py do it. */
static void dump_native_stack(const uintptr_t *sp)
{
    module_range();
    fprintf(stderr, "  Native stack (resolve RVAs against build/*.map):\n");
    int found = 0;
    for (int i = 0; i < 256; i++) {
        if (!in_module(sp[i])) continue;
        fprintf(stderr, "    [%3d] RVA 0x%llX\n", i,
            (unsigned long long)(sp[i] - g_mod_base));
        if (++found >= 16) break;
    }
    if (!found)
        fprintf(stderr, "    (no frames into this image found)\n");
}

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT) {
        /* The generated code emits __debugbreak() for x86 INT3 (translates
         * to a native int3 too). Standard INT semantics: the exception's
         * saved RIP already points to the instruction AFTER the 1-byte
         * int3 - no adjustment needed. (An earlier version of this handler
         * incorrectly did Rip += 1 here, which skipped an extra byte into
         * the middle of the next instruction and corrupted execution.) */
        fprintf(stderr, "[BREAKPOINT] hit at RIP=0x%llX (RVA=0x%llX) - continuing\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)(ep->ContextRecord->Rip - (uintptr_t)GetModuleHandleA(NULL)));
        fflush(stderr);
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        print_rip("[CRASH] Access violation at", ep->ContextRecord->Rip);
        fprintf(stderr, ", fault addr=0x%llX (%s)\n",
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        dump_native_stack((const uintptr_t *)ep->ContextRecord->Rsp);
        fflush(stderr);
    }

    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_INT_DIVIDE_BY_ZERO) {
        print_rip("[CRASH] Integer divide-by-zero at", ep->ContextRecord->Rip);
        fprintf(stderr, "\n");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        dump_native_stack((const uintptr_t *)ep->ContextRecord->Rsp);
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── Hang watchdog ─────────────────────────────────────────── */

/*
 * TEMPORARY DIAGNOSTIC: some bugs manifest as a silent infinite loop
 * entirely within recompiled game/CRT code, never calling into the
 * kernel bridge - so there's no natural hook point to count calls from
 * (unlike the lock-bootstrap recursion, caught via a counter in
 * bridge_RtlEnterCriticalSection). This watchdog thread sleeps, then
 * suspends the main thread from the outside and dumps its instruction
 * pointer plus a scan of the stack for addresses that look like they're
 * within this module - resolve against build/*.map's "Publics by Value"
 * the same way as every other RVA in this codebase. Remove once no
 * longer needed (not meant to ship in a release build).
 */
#define WATCHDOG_TIMEOUT_MS 8000
#define ICALL_TRACE_SIZE 16

extern volatile uint32_t g_icall_trace[ICALL_TRACE_SIZE];
extern volatile uint32_t g_icall_trace_idx;
extern volatile uint64_t g_icall_count;

static HANDLE g_watchdog_main_thread = NULL;

static unsigned __stdcall watchdog_thread_proc(void *arg)
{
    (void)arg;
    Sleep(WATCHDOG_TIMEOUT_MS);

    if (!g_watchdog_main_thread) return 0;

    fprintf(stderr, "\n[WATCHDOG] No progress after %d ms - main thread likely hung.\n", WATCHDOG_TIMEOUT_MS);
    fprintf(stderr, "[WATCHDOG] Total ICALL dispatches: %llu\n", (unsigned long long)g_icall_count);
    fprintf(stderr, "[WATCHDOG] Last %d ICALL targets (ring buffer, safe to read without suspending anything):\n", ICALL_TRACE_SIZE);
    for (int i = 0; i < ICALL_TRACE_SIZE; i++) {
        int idx = (g_icall_trace_idx - ICALL_TRACE_SIZE + i) & (ICALL_TRACE_SIZE - 1);
        fprintf(stderr, "  [%2d] 0x%08X\n", i, g_icall_trace[idx]);
    }
    fflush(stderr);

    /* SuspendThread + GetThreadContext causes a secondary crash here
     * (confirmed twice now - possibly a race, since SuspendThread's
     * effect can be delayed until the target returns to user mode, so
     * the main thread may keep running briefly with a torn context).
     * Disabled by default; the ICALL trace above needs none of this.
     * Re-enable only to hunt a specific quiet hang, and expect a
     * secondary access violation right after the RIP/stack dump prints -
     * that's fine, the diagnostics print first. */
#if 0
    SuspendThread(g_watchdog_main_thread);

    CONTEXT ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.ContextFlags = CONTEXT_FULL;
    if (GetThreadContext(g_watchdog_main_thread, &ctx)) {
        uintptr_t base = (uintptr_t)GetModuleHandleA(NULL);
        fprintf(stderr, "[WATCHDOG] RIP=0x%llX (RVA=0x%llX)\n",
            (unsigned long long)ctx.Rip, (unsigned long long)(ctx.Rip - base));
        fprintf(stderr, "[WATCHDOG] Stack scan (values in-range for this module, RSP=0x%llX):\n",
            (unsigned long long)ctx.Rsp);
        uintptr_t *sp = (uintptr_t *)ctx.Rsp;
        int printed = 0;
        for (int i = 0; i < 4096 && printed < 60; i++) {
            uintptr_t v = sp[i];
            if (v >= base && v < base + 0x02000000) {
                fprintf(stderr, "  [%4d] RVA=0x%llX\n", i, (unsigned long long)(v - base));
                printed++;
            }
        }
        fflush(stderr);
    } else {
        fprintf(stderr, "[WATCHDOG] GetThreadContext failed: %lu\n", GetLastError());
        fflush(stderr);
    }
#endif

    /* Diagnostics captured - terminate rather than resume, since resuming
     * just continues the same infinite loop and we already have what we
     * need. */
    TerminateProcess(GetCurrentProcess(), (UINT)-2);
    return 0;
}

static void watchdog_arm(void)
{
    DuplicateHandle(GetCurrentProcess(), GetCurrentThread(),
        GetCurrentProcess(), &g_watchdog_main_thread,
        0, FALSE, DUPLICATE_SAME_ACCESS);
    _beginthreadex(NULL, 0, watchdog_thread_proc, NULL, 0, NULL);
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== X-Men Legends - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /*
     * sub_0019EB69 (CRT boot code) reads Xbox VA 0x0044B0D8 and
     * self-relaunches via HalReturnToFirmware if it's zero. The XBE ships
     * it as zero with no writer anywhere in the game's code, so on real
     * hardware something outside the XBE (kernel/firmware) must set it
     * before this check runs - our runtime doesn't emulate that. Pre-set
     * it here so the game's own check passes and skips the relaunch we
     * can't otherwise satisfy. See recomp_manual.c history for the trace
     * that found this (thread routine 0x0019F196 -> sub_001A3211 ->
     * sub_0019EC8C -> HalReturnToFirmware, ordinal 49).
     */
    *(uint32_t *)((uint8_t *)g_xbox_mem_offset + 0x0044B0D8) = 1;

    /*
     * CRT lazy lock-table bootstrap: sub_003455D4 (creates a numbered CRT
     * lock on first use, e.g. for the heap) always acquires "lock #10"
     * first to protect the shared lock table - including when lock #10
     * itself is what's being created. Real CRT startup (_mtinit, before
     * main()/WinMain()) eagerly pre-initializes lock #10 so this
     * self-reference never actually recurses on real hardware; we skip
     * full CRT startup, so the first lazy lock creation recursed forever
     * (sub_00345674 <-> sub_003455D4) until the native stack overflowed.
     * Pre-create lock #10's CRITICAL_SECTION and seed the lock table slot
     * ourselves. Table layout: slot N lives at Xbox VA 0x0047A550 + N*8;
     * a non-null slot means "already initialized" to both functions.
     */
    {
        uint32_t cs_va = xbox_HeapAlloc(sizeof(CRITICAL_SECTION), 4);
        InitializeCriticalSection((LPCRITICAL_SECTION)((uint8_t *)g_xbox_mem_offset + cs_va));
        *(uint32_t *)((uint8_t *)g_xbox_mem_offset + 0x0047A5A0) = cs_va;  /* slot 10 = 0x47a550 + 10*8 */
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    watchdog_arm();

    recomp_func_t entry = recomp_lookup(YOUR_GAME_ENTRY_POINT);
    if (!entry) {
        fprintf(stderr, "Entry point 0x%08X not found in dispatch table!\n", YOUR_GAME_ENTRY_POINT);
        return 1;
    }
    entry();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
