/**
 * YOUR_GAME_NAME - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       YOUR_GAME_NAME
 *   Title ID:    0x00000000
 *   Base addr:   0x00010000
 *   Entry point: 0x00000000
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <process.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x001A1C97  /* XBE entry point VA */
#define YOUR_GAME_XBE_PATH      "game\\default.xbe"
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Dispatch table lookups (generated by recomp pipeline) */
typedef void (*recomp_func_t)(void);
extern recomp_func_t recomp_lookup(uint32_t xbox_va);

/* ── Crash-report helpers ──────────────────────────────────── */

/*
 * Actual load range of this executable.
 *
 * ASLR means we are NOT at the PE header's preferred base of 0x140000000 -
 * a 64-bit EXE typically lands near 0x7FF6'00000000. An earlier version of
 * the stack walk below filtered frames against the preferred base, so it
 * matched nothing and printed an empty stack on every crash, and the RVA in
 * the crash line was computed unconditionally and so was meaningless
 * whenever the fault was inside a system DLL.
 */
static uintptr_t g_mod_base;
static uintptr_t g_mod_end;

static void module_range(void)
{
    if (g_mod_base) return;
    HMODULE m = GetModuleHandleA(NULL);
    IMAGE_DOS_HEADER *dos = (IMAGE_DOS_HEADER *)m;
    IMAGE_NT_HEADERS *nt = (IMAGE_NT_HEADERS *)((uint8_t *)m + dos->e_lfanew);
    g_mod_base = (uintptr_t)m;
    g_mod_end = g_mod_base + nt->OptionalHeader.SizeOfImage;
}

static int in_module(uintptr_t a)
{
    module_range();
    return a >= g_mod_base && a < g_mod_end;
}

/* Print RIP, and its RVA only when the RVA actually means something. When the
 * fault is inside a system DLL - a bad pointer handed to memcpy, say - name
 * that DLL instead, because an RVA against our base would be garbage. */
static void print_rip(const char *what, uintptr_t rip)
{
    module_range();
    if (in_module(rip)) {
        fprintf(stderr, "%s RIP=0x%llX (RVA=0x%llX)",
            what, (unsigned long long)rip,
            (unsigned long long)(rip - g_mod_base));
        return;
    }
    HMODULE owner = NULL;
    char name[MAX_PATH] = "<unknown module>";
    if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                           GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                           (LPCSTR)rip, &owner) && owner) {
        GetModuleFileNameA(owner, name, sizeof name);
    }
    fprintf(stderr, "%s RIP=0x%llX (NOT in this image - inside %s;"
                    " the recompiled caller is in the stack below)",
        what, (unsigned long long)rip, name);
}

/* Print the call stack. Resolve the printed RVAs against build/*.map, or let
 * tools_data/triage_crash.py do it.
 *
 * Prefer CaptureStackBackTrace: it follows the real frame chain, so every
 * entry is a genuine caller. Scanning raw stack slots for anything that looks
 * like a return address also picks up *stale* values left by earlier calls,
 * and those had already sent one investigation chasing functions that were
 * never on the live path. The raw scan stays as a fallback, clearly labelled,
 * because deep recursion can exhaust what CaptureStackBackTrace will walk. */
static void dump_native_stack(const uintptr_t *sp)
{
    module_range();

    void *frames[62];
    USHORT n = CaptureStackBackTrace(0, 62, frames, NULL);
    if (n) {
        fprintf(stderr, "  Call stack, innermost first "
                        "(resolve RVAs against build/*.map):\n");
        for (USHORT i = 0; i < n; i++) {
            uintptr_t a = (uintptr_t)frames[i];
            if (in_module(a))
                fprintf(stderr, "    [%2u] RVA 0x%llX\n", i,
                    (unsigned long long)(a - g_mod_base));
        }
    }

    fprintf(stderr, "  Raw stack scan (may include stale return addresses):\n");
    int found = 0;
    for (int i = 0; i < 256; i++) {
        if (!in_module(sp[i])) continue;
        fprintf(stderr, "    [%3d] RVA 0x%llX\n", i,
            (unsigned long long)(sp[i] - g_mod_base));
        if (++found >= 16) break;
    }
    if (!found)
        fprintf(stderr, "    (no frames into this image found)\n");

    /* Same reason the watchdog path calls this: the per-target reject counts
     * are registered with atexit(), and neither a crash nor a watchdog kill
     * ever reaches exit handlers. On 2026-08-06 a 12-million-call spin was
     * invisible on the crash path for exactly this reason, having just been
     * diagnosed on the hang path by the same dump. A diagnostic that only
     * prints on the one path that does not happen is not a diagnostic. */
    recomp_icall_reject_dump();
    recomp_coverage_dump();
    recomp_alloc_dump();
    fflush(stderr);
}

/* ── recomp_where: probe-callable backtrace ─────────────────── */

/*
 * "Who called me?" used to be answerable only from a crash or a failed
 * indirect call, because dump_native_stack ran solely from those two paths.
 * Everywhere else the question cost a guess, and guesses have been wrong here
 * before - one investigation chased a caller that was never on the live path.
 *
 * This exposes the same real frame walk to any probe. Declared in
 * recomp_types.h next to the other recomp_* hooks.
 *
 * Rate limited per tag, because the interesting call is almost always one of
 * the first few and an unlimited probe inside a loop buries it. The return
 * value is the 1-based call number for this tag, so a probe can single out the
 * first occurrence:
 *
 *     if (recomp_where("unwind", 4, rec, MEM32(rec+4), MEM32(rec+8),
 *                      MEM32(rec+0xC)) == 1) { ... }
 *
 * Counting continues past the limit; only printing stops. The final count is
 * reported by recomp_where_summary() at exit, so a probe that stopped printing
 * still tells you how often it fired - a silent probe and a never-hit probe
 * have looked identical here before, and that cost a wrong conclusion.
 */
#define WHERE_TAGS 16

static struct {
    const char *tag;
    unsigned    hits;
    unsigned    limit;
} g_where[WHERE_TAGS];

static int g_where_used;
static int g_where_atexit;

void recomp_where_summary(void);   /* registered with atexit below */

unsigned recomp_where(const char *tag, unsigned limit,
                      uint32_t a, uint32_t b, uint32_t c, uint32_t d)
{
    int i;
    for (i = 0; i < g_where_used; i++)
        if (g_where[i].tag == tag || strcmp(g_where[i].tag, tag) == 0)
            break;
    if (i == g_where_used) {
        if (g_where_used >= WHERE_TAGS)
            return 0;                     /* out of slots - stay silent */
        g_where[i].tag = tag;
        g_where[i].hits = 0;
        g_where[i].limit = limit;
        g_where_used++;
    }

    if (!g_where_atexit) {          /* report totals however we exit */
        g_where_atexit = 1;
        atexit(recomp_where_summary);
    }

    unsigned n = ++g_where[i].hits;
    if (limit && n > limit)
        return n;                         /* still counting, no longer printing */

    module_range();
    fprintf(stderr, "[WHERE:%s] #%u  %08X %08X %08X %08X\n",
            tag, n, a, b, c, d);

    void *frames[24];
    /* Skip frame 0: it is recomp_where itself, never the answer. */
    USHORT got = CaptureStackBackTrace(1, 24, frames, NULL);
    for (USHORT k = 0; k < got; k++) {
        uintptr_t addr = (uintptr_t)frames[k];
        if (in_module(addr))
            fprintf(stderr, "    [%2u] RVA 0x%llX\n", k,
                    (unsigned long long)(addr - g_mod_base));
    }
    fflush(stderr);
    return n;
}

void recomp_where_summary(void)
{
    if (!g_where_used)
        return;
    fprintf(stderr, "\n[WHERE] final counts:\n");
    for (int i = 0; i < g_where_used; i++)
        fprintf(stderr, "  %-24s %u hit(s)%s\n", g_where[i].tag,
                g_where[i].hits,
                (g_where[i].limit && g_where[i].hits > g_where[i].limit)
                    ? " (printing was capped)" : "");
    fflush(stderr);
}

/*
 * A callee returned with ebx, esi or edi changed. See recomp_types.h.
 *
 * Reported per callee, once each, with the backtrace that names the caller.
 * Once-each matters: the interesting callee is usually invoked thousands of
 * times, and a per-call report buries the one that runs first.
 *
 * Lifter fragments are expected to trip this. The lifter splits some
 * functions at branch targets, and a fragment's pushes are matched by a pop
 * in a sibling, so in isolation it looks unbalanced while the pair is fine.
 * Cross-check a name against find_reg_clobbers.py before believing it.
 */
void recomp_abi_violation(const char *callee,
                          uint32_t ebx0, uint32_t esi0, uint32_t edi0)
{
    static const char *seen[64];
    static int n_seen;

    for (int i = 0; i < n_seen; i++)
        if (seen[i] == callee)
            return;
    if (n_seen < 64)
        seen[n_seen++] = callee;

    fprintf(stderr, "[ABI] %s did not restore:", callee);
    if (g_ebx != ebx0) fprintf(stderr, "  ebx %08X->%08X", ebx0, g_ebx);
    if (g_esi != esi0) fprintf(stderr, "  esi %08X->%08X", esi0, g_esi);
    if (g_edi != edi0) fprintf(stderr, "  edi %08X->%08X", edi0, g_edi);
    fprintf(stderr, "\n");

    module_range();
    void *frames[12];
    USHORT got = CaptureStackBackTrace(1, 12, frames, NULL);
    for (USHORT k = 0; k < got; k++) {
        uintptr_t a = (uintptr_t)frames[k];
        if (in_module(a))
            fprintf(stderr, "    [%2u] RVA 0x%llX\n", k,
                    (unsigned long long)(a - g_mod_base));
    }
    fflush(stderr);
}

/*
 * A call left esp outside the simulated stack. See recomp_types.h.
 *
 * Reported once and once only: esp is already wrong by this point, so every
 * later call trips the same test and the first report is the only one that
 * names the cause.
 */
void recomp_esp_escape(const char *callee, uint32_t esp_before)
{
    static int reported;
    if (reported)
        return;
    reported = 1;

    fprintf(stderr, "[ESP] %s left esp outside the stack: %08X -> %08X"
                    "  (delta %+d)\n",
            callee, esp_before, g_esp, (int)(g_esp - esp_before));

    module_range();
    void *frames[16];
    USHORT got = CaptureStackBackTrace(1, 16, frames, NULL);
    for (USHORT k = 0; k < got; k++) {
        uintptr_t a = (uintptr_t)frames[k];
        if (in_module(a))
            fprintf(stderr, "    [%2u] RVA 0x%llX\n", k,
                    (unsigned long long)(a - g_mod_base));
    }
    fflush(stderr);
}

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* ── Memory write-watch ──────────────────────────────────────
 *
 * "Which code wrote to this address?" is normally unanswerable in a static
 * recompilation: the original instruction addresses are gone, and the write
 * may come from lifted code, the kernel bridge, or the runtime. Grepping for
 * the address only finds *literal* uses - it cannot see a write through a
 * register, which is exactly how the SEH chain head was being destroyed. The
 * one literal candidate provably never executed; the watch found the real
 * writer on the first run.
 *
 * How: mark the page read-only, let the write fault, name the instruction from
 * the VEH, then restore access and continue. Self-disarming, so the program
 * runs on normally afterwards.
 *
 * Configured at RUNTIME, so adding a watch costs no rebuild:
 *
 *     set RECOMP_WATCH=0:4:seh_head,0x5DD0E8:4:heap_handle
 *
 * Format is VA[:SIZE[:LABEL]], comma separated. VA is an Xbox virtual address
 * and may be decimal or 0x-hex. SIZE defaults to 4 and only affects the
 * reported range - protection is per 4 KB page, so a watch catches writes
 * anywhere in its page and reports the exact offset.
 *
 * Caveat worth knowing: disarming restores the whole page, so two watches
 * sharing a page disarm together. Watch distinct pages if that matters.
 */
#define WATCH_MAX 8

typedef struct {
    uintptr_t page_lo, page_hi;   /* host addresses, page aligned */
    uint32_t  va;                 /* xbox VA requested */
    uint32_t  size;
    int       armed;
    unsigned  near_miss;          /* writes elsewhere on the page, stepped over */
    unsigned  reports;            /* trace-mode reports emitted for this watch */
    uint32_t  skip;               /* matching writes to let past before reporting */
    uint32_t  seen;               /* matching writes so far */
    char      label[32];
} watch_t;

static watch_t      g_watch[WATCH_MAX];
static int          g_watch_n = 0;
static volatile int g_watch_any = 0;   /* fast path: skip the loop entirely */

/* Set while a neighbouring write is being single-stepped past; the trap that
 * follows re-protects this watch's page. See the write-watch branch below. */
static watch_t     *g_watch_pending = NULL;

/*
 * Trace mode: RECOMP_WATCH_TRACE=<n> reports every write to the watched bytes,
 * up to n, and never disarms.
 *
 * Without it a watch answers "who wrote here FIRST", and that turned out to be
 * the wrong question every single time on 2026-08-06. Guest 0x3C is written 9
 * times before the boot dies; the first was a harmless zero-fill and the value
 * that actually hangs the game was written later. Same story at 0x00F812B4 -
 * 15 writes from 8 different functions, and the watch was spent on write #1.
 * `skip` let me step past them one at a time, but only by re-running and
 * guessing a number, and it never printed WHAT was written.
 *
 * The value is not available when the fault fires - the write has not happened
 * yet. So the fault records what it is about to see, steps over, and the
 * single-step that follows reads the landed value and logs it. That yields a
 * full write history: offset, value, and writer, in order, in one run.
 */
static uint32_t     g_watch_trace_cap = 0;
static uint32_t     g_pend_va = 0;        /* xbox VA the pending write targets */
static uintptr_t    g_pend_rip = 0;       /* RIP of the instruction doing it */
static uintptr_t    g_pend_host = 0;      /* host address, to read the value */
static int          g_pend_is_trace = 0;

/* Parse RECOMP_WATCH and mark the requested pages read-only.
 * Called after the memory layout is populated - arming earlier would trip on
 * the runtime's own initialisation instead of the code under suspicion. */
static void watch_init(void)
{
    const char *spec = getenv("RECOMP_WATCH");
    if (!spec || !*spec) {
        return;
    }

    /* Trace mode reports every write to the watched bytes, with the value, and
     * never disarms. See g_watch_trace_cap. */
    const char *tr = getenv("RECOMP_WATCH_TRACE");
    if (tr && *tr) {
        g_watch_trace_cap = (uint32_t)strtoul(tr, NULL, 0);
        fprintf(stderr, "[WATCH] trace mode: up to %u write(s) per watch, "
                        "never disarming\n", g_watch_trace_cap);
    }

    char buf[512];
    strncpy(buf, spec, sizeof buf - 1);
    buf[sizeof buf - 1] = '\0';

    for (char *tok = strtok(buf, ","); tok && g_watch_n < WATCH_MAX;
         tok = strtok(NULL, ",")) {
        char *colon = strchr(tok, ':');
        if (colon) *colon = '\0';

        uint32_t va = (uint32_t)strtoul(tok, NULL, 0);   /* 0 => auto-detect base */
        uint32_t size = 4;
        const char *label = "watch";

        uint32_t skip = 0;
        if (colon) {
            char *rest = colon + 1;
            char *colon2 = strchr(rest, ':');
            if (colon2) {
                *colon2 = '\0';
                label = colon2 + 1;
                /* Optional 4th field: how many matching writes to let past
                 * before reporting. The first write to a fresh heap block is
                 * the allocator zeroing it, which is correct and not the
                 * answer to any question worth asking - `:1` skips it. */
                char *colon3 = strchr(colon2 + 1, ':');
                if (colon3) {
                    *colon3 = '\0';
                    skip = (uint32_t)strtoul(colon3 + 1, NULL, 0);
                }
            }
            if (*rest) size = (uint32_t)strtoul(rest, NULL, 0);
        }

        watch_t *w = &g_watch[g_watch_n];
        uintptr_t host = (uintptr_t)va + (uintptr_t)g_xbox_mem_offset;
        w->page_lo = host & ~(uintptr_t)0xFFF;
        w->page_hi = ((host + size - 1) & ~(uintptr_t)0xFFF) + 0x1000;
        w->va = va;
        w->size = size;
        w->skip = skip;
        w->seen = 0;
        strncpy(w->label, label, sizeof w->label - 1);
        w->label[sizeof w->label - 1] = '\0';

        DWORD old = 0;
        if (VirtualProtect((void *)w->page_lo, w->page_hi - w->page_lo,
                           PAGE_READONLY, &old)) {
            w->armed = 1;
            g_watch_any = 1;
            g_watch_n++;
            fprintf(stderr, "[WATCH:%s] armed on xbox VA 0x%08X (%u bytes); "
                            "current value 0x%08X\n",
                    w->label, w->va, w->size,
                    *(volatile uint32_t *)host);
            if (w->skip)
                fprintf(stderr, "  (letting the first %u matching write(s) "
                                "past before reporting)\n", w->skip);
        } else {
            fprintf(stderr, "[WATCH:%s] VirtualProtect failed for VA 0x%08X: %lu\n",
                    w->label, va, GetLastError());
        }
        fflush(stderr);
    }
}

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT) {
        /* The generated code emits __debugbreak() for x86 INT3 (translates
         * to a native int3 too). Standard INT semantics: the exception's
         * saved RIP already points to the instruction AFTER the 1-byte
         * int3 - no adjustment needed. (An earlier version of this handler
         * incorrectly did Rip += 1 here, which skipped an extra byte into
         * the middle of the next instruction and corrupted execution.) */
        fprintf(stderr, "[BREAKPOINT] hit at RIP=0x%llX (RVA=0x%llX) - continuing\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)(ep->ContextRecord->Rip - (uintptr_t)GetModuleHandleA(NULL)));
        fflush(stderr);
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    /* Second half of the step-over: the neighbouring write has now completed,
     * so put the page back under guard and clear the trap flag. */
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_SINGLE_STEP
            && g_watch_pending) {
        DWORD old;
        watch_t *w = g_watch_pending;
        g_watch_pending = NULL;
        ep->ContextRecord->EFlags &= ~0x100u;

        /* The write has landed, so now the value can be read. This is the only
         * point where it exists - at fault time the store had not executed. */
        if (g_pend_is_trace) {
            g_pend_is_trace = 0;
            uint32_t val = *(volatile uint32_t *)g_pend_host;
            fprintf(stderr,
                    "[WATCH:%s] #%u  VA 0x%08X (+0x%X) = 0x%08X  from RVA=0x%llX\n",
                    w->label, w->reports, g_pend_va, g_pend_va - w->va, val,
                    (unsigned long long)(g_pend_rip
                        - (uintptr_t)GetModuleHandleA(NULL)));
            fflush(stderr);
        }

        if (w->armed)
            VirtualProtect((void *)w->page_lo, w->page_hi - w->page_lo,
                           PAGE_READONLY, &old);
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /* Write-watch: name whoever wrote here, then get out of the way. */
        if (g_watch_any && ep->ExceptionRecord->ExceptionInformation[0] == 1) {
            for (int i = 0; i < g_watch_n; i++) {
                watch_t *w = &g_watch[i];
                if (!w->armed || fault_addr < w->page_lo
                        || fault_addr >= w->page_hi) {
                    continue;
                }
                DWORD old;
                uintptr_t base = (uintptr_t)GetModuleHandleA(NULL);
                uint32_t hit_va = w->va + (uint32_t)(fault_addr
                                  - (w->page_lo + (w->va & 0xFFFu)));

                /*
                 * Protection is per page, but the question is almost always
                 * about specific bytes. Disarming on the first write anywhere
                 * in the page means a busy neighbour answers a question that
                 * was never asked - which is exactly what happened hunting
                 * the igMetaObject guard at 0x5BC508: a write to 0x5BC548,
                 * 64 bytes away, consumed the watch.
                 *
                 * So a write outside the watched bytes is stepped over
                 * instead: unprotect, set the trap flag, and re-protect on
                 * the single-step that follows. The watch survives to catch
                 * the write that was actually asked about.
                 */
                if (hit_va < w->va || hit_va >= w->va + w->size) {
                    w->near_miss++;
                    VirtualProtect((void *)w->page_lo,
                                   w->page_hi - w->page_lo,
                                   PAGE_READWRITE, &old);
                    g_watch_pending = w;
                    ep->ContextRecord->EFlags |= 0x100u;   /* TF */
                    return EXCEPTION_CONTINUE_EXECUTION;
                }

                /* Trace mode: log this write and stay armed, so the whole
                 * write history comes out of one run instead of one write per
                 * run with a hand-guessed skip count. */
                if (g_watch_trace_cap && w->reports < g_watch_trace_cap) {
                    w->reports++;
                    w->seen++;
                    g_pend_va = hit_va;
                    g_pend_rip = ep->ContextRecord->Rip;
                    g_pend_host = fault_addr;
                    g_pend_is_trace = 1;
                    VirtualProtect((void *)w->page_lo,
                                   w->page_hi - w->page_lo,
                                   PAGE_READWRITE, &old);
                    g_watch_pending = w;
                    ep->ContextRecord->EFlags |= 0x100u;   /* TF */
                    return EXCEPTION_CONTINUE_EXECUTION;
                }

                if (++w->seen <= w->skip) {
                    VirtualProtect((void *)w->page_lo,
                                   w->page_hi - w->page_lo,
                                   PAGE_READWRITE, &old);
                    g_watch_pending = w;
                    ep->ContextRecord->EFlags |= 0x100u;   /* TF */
                    fprintf(stderr, "[WATCH:%s] skipping matching write #%u "
                                    "from RVA=0x%llX\n", w->label, w->seen,
                            (unsigned long long)(ep->ContextRecord->Rip
                                - (uintptr_t)GetModuleHandleA(NULL)));
                    fflush(stderr);
                    return EXCEPTION_CONTINUE_EXECUTION;
                }

                w->armed = 0;
                VirtualProtect((void *)w->page_lo, w->page_hi - w->page_lo,
                               PAGE_READWRITE, &old);

                int still = 0;
                for (int j = 0; j < g_watch_n; j++) still |= g_watch[j].armed;
                g_watch_any = still;

                fprintf(stderr,
                        "[WATCH:%s] write to xbox VA 0x%08X from RIP=0x%llX "
                        "(RVA=0x%llX) - disarmed, continuing\n"
                        "  (%u write(s) elsewhere on the page were stepped "
                        "over to get here)\n",
                        w->label, hit_va,
                        (unsigned long long)ep->ContextRecord->Rip,
                        (unsigned long long)(ep->ContextRecord->Rip - base),
                        w->near_miss);

                void *frames[16];
                USHORT got = CaptureStackBackTrace(1, 16, frames, NULL);
                module_range();
                for (USHORT k = 0; k < got; k++) {
                    uintptr_t a = (uintptr_t)frames[k];
                    if (in_module(a))
                        fprintf(stderr, "    [%2u] RVA 0x%llX\n", k,
                                (unsigned long long)(a - g_mod_base));
                }
                fflush(stderr);
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        print_rip("[CRASH] Access violation at", ep->ContextRecord->Rip);
        fprintf(stderr, ", fault addr=0x%llX (%s)\n",
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        dump_native_stack((const uintptr_t *)ep->ContextRecord->Rsp);
        fflush(stderr);
    }

    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_INT_DIVIDE_BY_ZERO) {
        print_rip("[CRASH] Integer divide-by-zero at", ep->ContextRecord->Rip);
        fprintf(stderr, "\n");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        dump_native_stack((const uintptr_t *)ep->ContextRecord->Rsp);
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── Hang watchdog ─────────────────────────────────────────── */

/*
 * TEMPORARY DIAGNOSTIC: some bugs manifest as a silent infinite loop
 * entirely within recompiled game/CRT code, never calling into the
 * kernel bridge - so there's no natural hook point to count calls from
 * (unlike the lock-bootstrap recursion, caught via a counter in
 * bridge_RtlEnterCriticalSection). This watchdog thread sleeps, then
 * suspends the main thread from the outside and dumps its instruction
 * pointer plus a scan of the stack for addresses that look like they're
 * within this module - resolve against build/*.map's "Publics by Value"
 * the same way as every other RVA in this codebase. Remove once no
 * longer needed (not meant to ship in a release build).
 */
#define WATCHDOG_TIMEOUT_MS 8000
#define ICALL_TRACE_SIZE 16

extern volatile uint32_t g_icall_trace[ICALL_TRACE_SIZE];
extern volatile uint32_t g_icall_trace_idx;
extern volatile uint64_t g_icall_count;

static HANDLE g_watchdog_main_thread = NULL;

/* Kill the process after `ms`, no matter what else is stuck.
 *
 * The RIP capture below suspends the main thread, and if that thread is inside
 * fprintf - which it usually is, since the SAFE_STUB and ICALL logs sit on the
 * hot path of exactly the spins worth capturing - anything the watchdog prints
 * afterwards can block on the stdio lock forever. That turned an 8-second
 * diagnostic run into an indefinite hang twice. This guarantees an exit and
 * keeps whatever was flushed before the deadline. */
static unsigned __stdcall watchdog_deadline_proc(void *arg)
{
    static const char msg[] =
        "\n[WATCHDOG] hard deadline reached - terminating "
        "(any RIP capture above may be incomplete)\n";
    DWORD wrote;
    Sleep((DWORD)(uintptr_t)arg);
    /* WriteFile, NOT fprintf. This thread exists because the stdio lock is
     * suspect, so using the CRT here would block on the very lock it is meant
     * to rescue us from - which is exactly what happened on the first attempt:
     * the deadline never fired and the run had to be killed externally.
     * WriteFile goes straight to the handle and cannot be held up by the CRT. */
    WriteFile(GetStdHandle(STD_ERROR_HANDLE), msg, (DWORD)(sizeof msg - 1),
              &wrote, NULL);
    TerminateProcess(GetCurrentProcess(), (UINT)-3);
    return 0;
}

static void watchdog_arm_hard_deadline(unsigned ms)
{
    uintptr_t h = _beginthreadex(NULL, 0, watchdog_deadline_proc,
                                 (void *)(uintptr_t)ms, 0, NULL);
    if (h) CloseHandle((HANDLE)h);
}

static unsigned __stdcall watchdog_thread_proc(void *arg)
{
    (void)arg;
    Sleep(WATCHDOG_TIMEOUT_MS);

    if (!g_watchdog_main_thread) return 0;

    fprintf(stderr, "\n[WATCHDOG] No progress after %d ms - main thread likely hung.\n", WATCHDOG_TIMEOUT_MS);
    fprintf(stderr, "[WATCHDOG] Total ICALL dispatches: %llu\n", (unsigned long long)g_icall_count);
    fprintf(stderr, "[WATCHDOG] Last %d ICALL targets (ring buffer, safe to read without suspending anything):\n", ICALL_TRACE_SIZE);
    for (int i = 0; i < ICALL_TRACE_SIZE; i++) {
        int idx = (g_icall_trace_idx - ICALL_TRACE_SIZE + i) & (ICALL_TRACE_SIZE - 1);
        fprintf(stderr, "  [%2d] 0x%08X\n", i, g_icall_trace[idx]);
    }
    fflush(stderr);

    /* The per-target reject counts are registered with atexit(), but the hard
     * deadline below TerminateProcess()es us, so exit handlers never run and
     * that summary has never once been printed on the path that actually
     * happens. Print it here instead.
     *
     * It belongs on THIS thread, not the deadline thread: the dump uses
     * fprintf, and the deadline thread deliberately avoids stdio because the
     * spinning thread can be holding the lock (see watchdog_deadline_proc).
     * The ring-buffer dump immediately above proves fprintf works from here.
     *
     * Worth more than the ring buffer for this failure: the ring shows the
     * last 16 targets, which on a spin are all the same address, while the
     * counts say which target dominates across the whole run. */
    recomp_icall_reject_dump();
    recomp_coverage_dump();
    recomp_alloc_dump();
    fflush(stderr);

    /* Capturing the hung thread's RIP names the spinning function outright,
     * and on a QUIET loop - one that makes no kernel calls and no indirect
     * dispatches - it is the only instrument that works at all. It found the
     * unbounded tree walk in sub_001186A0 that a probe could never have seen.
     *
     * It is not free: SuspendThread + GetThreadContext causes a secondary
     * crash afterwards (confirmed repeatedly - SuspendThread's effect can be
     * delayed until the target re-enters user mode, so the main thread may run
     * on briefly with a torn context). The diagnostics print BEFORE that, so
     * the dump is always usable, but the run ends as a fault rather than a
     * hang and the smoke signals change shape.
     *
     * So it is opt-in at RUNTIME rather than compile time. It used to be
     * `#if 0`, which meant every use cost an edit, a rebuild and a revert -
     * three times in one session. Now:
     *
     *     set RECOMP_HANG_RIP=1        (cmd)
     *     $env:RECOMP_HANG_RIP=1       (PowerShell)
     *
     * triage_crash.py symbolises the result and prints this hint when the
     * variable was not set. */
    if (!getenv("RECOMP_HANG_RIP")) {
        fprintf(stderr, "[WATCHDOG] set RECOMP_HANG_RIP=1 to capture the hung "
                        "thread's RIP (names the spinning function)\n");
        fflush(stderr);
    } else {
        /* HARD DEADLINE FIRST. Everything below is best-effort diagnostics on
         * a process that is already wedged, and it has hung outright more than
         * once - suspending a thread that holds the stdio lock is inherently
         * racy and no amount of ordering makes it safe in every case. So arm a
         * killer that fires regardless, and let the capture be allowed to fail.
         * Whatever printed before the deadline is still in the log, which is
         * the entire value; an unbounded diagnostic that wedges the run is
         * worth less than a partial one that always terminates. */
        watchdog_arm_hard_deadline(3000);

        /* SNAPSHOT, RESUME, then print - in that order, and never print while
         * the target is suspended.
         *
         * The main thread in a spin is usually inside fprintf itself (the
         * SAFE_STUB and ICALL logs sit right on the hot path), so it holds the
         * stdio lock. Suspending it and then calling fprintf here deadlocks on
         * that lock, and the process hangs forever with no output at all -
         * measured, and worse than the "secondary access violation" the old
         * comment warned about, which was very likely this same hazard wearing
         * a different hat.
         *
         * Copying the CONTEXT out first costs nothing: it is a value, still
         * valid after the thread runs on, and the RIP it holds is the sample we
         * came for. Also read the stack into a local buffer before resuming,
         * since walking it afterwards would race the thread that owns it. */
        CONTEXT ctx;
        memset(&ctx, 0, sizeof(ctx));
        ctx.ContextFlags = CONTEXT_FULL;

        uintptr_t frames[4096];
        size_t nframes = 0;
        BOOL got;

        SuspendThread(g_watchdog_main_thread);
        got = GetThreadContext(g_watchdog_main_thread, &ctx);
        if (got) {
            /* A torn or wild RSP can point anywhere, so guard the copy with
             * SEH rather than a validity predicate: IsBadReadPtr was tried
             * here and the watchdog still died mid-print, because it reports
             * on page presence and cannot promise the next slot is readable.
             * __try keeps whatever was copied before the first fault. */
            uintptr_t *sp = (uintptr_t *)ctx.Rsp;
            __try {
                for (; nframes < 4096; nframes++)
                    frames[nframes] = sp[nframes];
            } __except (EXCEPTION_EXECUTE_HANDLER) {
                /* nframes holds however many slots were readable. */
            }
        }
        ResumeThread(g_watchdog_main_thread);

        if (got) {
            uintptr_t base = (uintptr_t)GetModuleHandleA(NULL);
            fprintf(stderr, "[WATCHDOG] RIP=0x%llX (RVA=0x%llX)\n",
                (unsigned long long)ctx.Rip,
                (unsigned long long)(ctx.Rip - base));
            fprintf(stderr, "[WATCHDOG] Stack scan (values in-range for this "
                            "module, RSP=0x%llX):\n",
                (unsigned long long)ctx.Rsp);
            int printed = 0;
            for (size_t i = 0; i < nframes && printed < 60; i++) {
                uintptr_t v = frames[i];
                if (v >= base && v < base + 0x02000000) {
                    fprintf(stderr, "  [%4zu] RVA=0x%llX\n", i,
                            (unsigned long long)(v - base));
                    printed++;
                }
            }
            fflush(stderr);
        } else {
            fprintf(stderr, "[WATCHDOG] GetThreadContext failed: %lu\n",
                    GetLastError());
            fflush(stderr);
        }
    }   /* RECOMP_HANG_RIP */

    /* Diagnostics captured - terminate rather than resume, since resuming
     * just continues the same infinite loop and we already have what we
     * need. */
    TerminateProcess(GetCurrentProcess(), (UINT)-2);
    return 0;
}

static void watchdog_arm(void)
{
    DuplicateHandle(GetCurrentProcess(), GetCurrentThread(),
        GetCurrentProcess(), &g_watchdog_main_thread,
        0, FALSE, DUPLICATE_SAME_ACCESS);
    _beginthreadex(NULL, 0, watchdog_thread_proc, NULL, 0, NULL);
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== X-Men Legends - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Arm any write-watches requested via RECOMP_WATCH. Done here because the
     * memory layout is now populated - a watch armed earlier would fire on the
     * runtime's own initialisation rather than on the code under suspicion. */
    watch_init();


    /*
     * sub_0019EB69 (CRT boot code) reads Xbox VA 0x0044B0D8 and
     * self-relaunches via HalReturnToFirmware if it's zero. The XBE ships
     * it as zero with no writer anywhere in the game's code, so on real
     * hardware something outside the XBE (kernel/firmware) must set it
     * before this check runs - our runtime doesn't emulate that. Pre-set
     * it here so the game's own check passes and skips the relaunch we
     * can't otherwise satisfy. See recomp_manual.c history for the trace
     * that found this (thread routine 0x0019F196 -> sub_001A3211 ->
     * sub_0019EC8C -> HalReturnToFirmware, ordinal 49).
     */
    *(uint32_t *)((uint8_t *)g_xbox_mem_offset + 0x0044B0D8) = 1;

    /*
     * CRT lazy lock-table bootstrap: sub_003455D4 (creates a numbered CRT
     * lock on first use, e.g. for the heap) always acquires "lock #10"
     * first to protect the shared lock table - including when lock #10
     * itself is what's being created. Real CRT startup (_mtinit, before
     * main()/WinMain()) eagerly pre-initializes lock #10 so this
     * self-reference never actually recurses on real hardware; we skip
     * full CRT startup, so the first lazy lock creation recursed forever
     * (sub_00345674 <-> sub_003455D4) until the native stack overflowed.
     * Pre-create lock #10's CRITICAL_SECTION and seed the lock table slot
     * ourselves. Table layout: slot N lives at Xbox VA 0x0047A550 + N*8;
     * a non-null slot means "already initialized" to both functions.
     */
    {
        uint32_t cs_va = xbox_HeapAlloc(sizeof(CRITICAL_SECTION), 4);
        InitializeCriticalSection((LPCRITICAL_SECTION)((uint8_t *)g_xbox_mem_offset + cs_va));
        *(uint32_t *)((uint8_t *)g_xbox_mem_offset + 0x0047A5A0) = cs_va;  /* slot 10 = 0x47a550 + 10*8 */
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    watchdog_arm();

    recomp_func_t entry = recomp_lookup(YOUR_GAME_ENTRY_POINT);
    if (!entry) {
        fprintf(stderr, "Entry point 0x%08X not found in dispatch table!\n", YOUR_GAME_ENTRY_POINT);
        return 1;
    }
    entry();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
